### ISSUE TITLE
Please update your gist 

### ISSUE THREAD

**Issue by billyprice1** [mkuba50/techbench-dump#1]
http://downloads.ibilly.top/windows/techbench.md

You can change the download link from downloads.ibilly.top/get.php to yours

**Comment by mkuba50** [comment]
Can you write more clearly what do you want? I have no idea what do you mean.

**Comment by billyprice1** [comment]
Your old gist with the download links are wrong as there are more

**Comment by mkuba50** [comment]
Gist at https://gist.github.com/mkuba50/27c909501cbc2a4f169be4b4075a66ff is rarely updated backup of http://mdl-tb.ct8.pl and currently is up to date.

I always use http://mdl-tb.ct8.pl/dump.md to update it.
